<script>
    import { report } from '../store';

</script>

<div>
    <h2>Summary</h2>
    <table>
        <tr>
            <td>Generated By</td>
            <td>fastp {$report.summary?.fastp_version}</td>
        </tr>
        <tr>
            <td>Sequencing Type</td>
            <td>{$report.summary?.sequencing}</td>
        </tr>
    </table>
    <h3>Read Quality</h3>
    <table>
        <tr>
            <td>Passed Filters</td>
            <td>fastp {$report.summary?.fastp_version}</td>
        </tr>
        <tr>
            <td>Sequencing Type</td>
            <td>{$report.summary?.sequencing}</td>
        </tr>
    </table>
    {JSON.stringify($report.summary)}
</div>

<style lang='scss'>
    table, tr, td {
        border: solid 1px black;
    }
    td {
        padding: 0.5em 1em;
    }
    td:first-of-type {
        background: black;
        color: white;
    }
</style>
